### ISSUE TITLE
能否加上下面的部分功能

### ISSUE THREAD

**Issue by teethen** [YuanJianTing/WinForm.UI#1]
FTable控件能添加以下功能吗？特别是1-3。
1、列宽可通过鼠标自行拖动调整。
2、行和列拖拽移动其顺序，拖拽一行时上下移动该行，拖拽一列时左右移动该列。
3、列头点击排序事件。
4、单元格显示图片或者副文本。

**Comment by YuanJianTing** [comment]
谢谢,这些功能后面会考虑添加。
暂时没有时间安排；

**Comment by YuanJianTing** [comment]
table已添加以上功能。但未经过详细测试，可能会有bug；

**Comment by xingqingxiang** [comment]
太感谢了，我帮你测试bug。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuanJianTing/WinForm.UI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 上午8:45
收件人:&nbsp;"YuanJianTing/WinForm.UI"<WinForm.UI@noreply.github.com&gt;;
抄送:&nbsp;"飞翔的企鹅"<547013892@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YuanJianTing/WinForm.UI] 能否加上下面的部分功能 (#1)





 
table已添加以上功能。但未经过详细测试，可能会有bug；

**Comment by teethen** [comment]
> table已添加以上功能。但未经过详细测试，可能会有bug；

太感谢了，我帮你测试bug。
