### ISSUE TITLE
Table点击排序事件

### ISSUE THREAD

**Issue by teethen** [YuanJianTing/WinForm.UI#2]
只有滚动条(垂直滚动条)在最顶端时，点击排序列，才响应排序事件。滚动条往下滚动一段距离后，再点击排序列头时，则无响应排序事件。
![QQ截图20201023170713](https://user-images.githubusercontent.com/12929494/96983311-ada97e80-1552-11eb-94f0-2bdbf93caea6.png)

**Comment by YuanJianTing** [comment]
thank you！ 新版本已修复。

**Comment by YuanJianTing** [comment]
已修复
